language: python
python:
- 3.5
- 3.6
- 3.6-dev
- 3.7-dev
- nightly

# Scripts to install dependencies
install:
- pip install -e .[test]

# Run tests
script:
- pre-commit run --all-files
- nosetests -svv

deploy:
  provider: pypi
  user: webknjaz
  password:
    secure: tEur3AytUMER9L7iVqGwRmprbGRj5c76EGFow6Fbv+y61bEJuz5g7ikrRK0Xgr0jMVgckjEaK8+9F7HKJ15zHiJpOJdKKtkEiMTMZaxd48IewnjJypNYElFLNMiSwaHUJy0k0Pz/dYmV5qjWkPP+nmKnZJSuuv4PkUQYxyCsiXvrF08fN3m6ODtr4JIeMltHWuxbD7vQu8/Grdd5PHee2XGzoxFP5vfgkZ0o+YKgfDzsJv8YdsKfUECQuiG1Wn8VepDRPtx0wkTraSlia8EzxBfupMEPkPFH3gzea37HVo/rVNEJiwd4se6gwde+sPTrkoosgTYhBrTNO/6k2jSdiJXSXLXGhd52YJ8S492io7oK3/lgOkUGf8qtOYNak/W0Kyt8PorS5OsqnHBDskRiBnbDae/JJ7h3RWXfnXdSiy05YsNBb1sOpM5ViWFJyAVwa3y3KEHYhqCHbQAlwDGQI7faKVl+lpSfz82rgrlguGPhpigs9Zdd6fKl8J36M4XRE3WgwAcoN8whpB52XzKUWiKKMM78qry6fUa01NXMUBtb8NUgqv1bHslm43V3tLH1XsF3G4IZVmR8+6c118yZHTMUw6zp1yMY2a1GE5/CZOHKxkcSmiYZHhuj5zbfmFt5P3rRt0y/TBZlrLG4EPnDZ/nhTP/o8CRTdsxjZZNk+4Y=
  distributions: release
  skip_upload_docs: true
